PRINCIPAL=userA@REALM
KEYTAB=/etc/security/keytabs/userA.keytab

# Use KCM for credential caching, with a unique cache name to avoid conflicts
# This should be system configured credential cache, other options include:
# CACHE=KEYRING:persistent:0:AAA
CACHE=KCM:0:AAA

SERVER=serverA
SHARE=share1
MOUNT=/mnt/share1

CIFS_UID=1000
CIFS_GID=1000
DIR_MODE=0755
FILE_MODE=0644

# If not set it defaults to 3
VERS=3.1.1
SEC=krb5
IOCHARSET=utf8
CACHE_MODE=strict

AUTO_RENEW=yes
